# from langchain_core.prompts import ChatPromptTemplate
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from sql_ai_agent2.db_handler import get_tbl_attr
    

def set_prompt_template():
    """
    Build a LangChain ChatPromptTemplate for SQL generation.

    Parameters
    ----------
    question : str
        Natural language question describing the SQL request.
    tbl_name : str
        Name of the SQL table.
    schema : str
        Table schema (column definitions).
    additional_context : str, optional
        Extra system context. Defaults to empty string.

    Returns
    -------
    ChatPromptTemplate
        A LangChain prompt template ready to be invoked.
    """

    system_template = """
Given the following SQL table, your job is to write queries given a user’s request.
Return just the SQL query as plain text, without additional text, and don't use markdown format.
I am quering the data against a {database} database, please make sure you are using the {database} SQL dialects. 
Please ensure that the field names in the query are enclosed in double quotes.
{additional_context}
CREATE TABLE {tbl_name} ({schema})
""".strip()

    user_template = "Write a SQL query that returns: {question}"

    messages = [
        ("system", system_template),
        ("user", user_template)
    ]

    prompt_template = ChatPromptTemplate.from_messages(messages)

    return prompt_template


# def debug_prompt_template():
#     system_template = """
#         You are You are a data engineer, and your role is to debug and fix 
#         errors with SQL queries generated by an SQL AI agent based on a user question. 
#         Return just the SQL query as plain text, without additional text, and don't use markdown format.    
#         You are working with a {database} database with the following table:
#         CREATE TABLE {tbl_name} ({schema})
#         """
#     user_template = """
#         The user asked the following question - {question}, and the SQL AI agent created this query:
#         {query}
#         When sending this query, it returns the following error:
#         {error}
#         Please debug the query error and return a fixed query.
#         """
#     messages = [
#         ("system", system_template),
#         ("user", user_template)
#     ]

#     debug_prompt_template = ChatPromptTemplate.from_messages(messages)

#     return debug_prompt_template 

def debug_prompt_template():
    system_template = """
You are a senior data engineer debugging SQL queries.

Your task:
- Fix the SQL query so it executes successfully.
- Do NOT repeat mistakes from previous attempts.
- Use the debug history to identify patterns or incorrect assumptions.

Rules:
- Return ONLY the corrected SQL query.
- No explanations, no markdown.

Database: {database}
Table:
CREATE TABLE {tbl_name} ({schema})
"""

    user_template = """
User question:
{question}

Previous debug attempts:
{debug_memory}

Latest failed query:
{query}

Error message:
{error}

Based on the history above, fix the query.
"""

    messages = [
        ("system", system_template),
        ("user", user_template)
    ]

    return ChatPromptTemplate.from_messages(messages)






    
    

